import "./app.css"

function App() {
  return (
    <div>
      <h1>calculator</h1>
      <table className="Center">
        <tbody>
          <tr>
            <td>
              11
            </td>
            <td>
              12
            </td>
            <td>
              13
            </td>
            <td>
              14
            </td>
          </tr>
          <tr>
            <td>
              21
            </td>
            <td>
              22
            </td>
            <td>
              23
            </td>
            <td>
              24
            </td>
          </tr>
          <tr>
            <td>
              31
            </td>
            <td>
              32
            </td>
            <td>
              33
            </td>
            <td>
              34
            </td>
          </tr>
          <tr>
            <td>
              41
            </td>
            <td>
              42
            </td>
            <td>
              43
            </td>
            <td>
              44
            </td>
          </tr>
          <tr>
            <td>
              51
            </td>
            <td>
              52
            </td>
            <td>
              53
            </td>
            <td>
              54
            </td>
          </tr>
          <tr>
            <td>
              61
            </td>
            <td>
              62
            </td>
            <td>
              63
            </td>
            <td>
              64
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}

export default App
